on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-packages:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download OpenJDK 17 for macOS
        shell: bash
        run: |
          set -Eeuo pipefail
          jdksPath="$HOME/.jdks"
          mkdir -p "$jdksPath"
          link="https://download.oracle.com/java/17/archive/jdk-17.0.12_macos-x64_bin.tar.gz"
          curl --location "$link" --output "$jdksPath/jdk.tar.gz"
          tar -xf "$jdksPath/jdk.tar.gz" -C "$jdksPath"
          extracted=$(ls "$jdksPath" | grep jdk-17)
          echo "JAVA_HOME=$jdksPath/$extracted/Contents/Home" >> "$GITHUB_ENV"
          echo "PATH=$jdksPath/$extracted/Contents/Home/bin:$PATH" >> "$GITHUB_ENV"

      - name: Gradle Build
        run: ./gradlew
        shell: bash

      - name: Build package for macOS using gradle
        shell: bash
        run: ./gradlew desktop:app:createReleaseFolderForCi

      - name: Install create-dmg
        run: |
          brew install create-dmg

      - name: Create DMG
        shell: bash
        run: |
          create-dmg \
            --volname "ABDownloadManager" \
            --background "desktop/app/resources/installer/dmg_background.png" \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "ABDownloadManager.app" 100 150 \
            --app-drop-link 450 150 \
            "ABDownloadManager.dmg" \
            desktop/app/build/compose/binaries/main-release/app/

      - name: Prepare release folder
        run: |
          mkdir -p release
          cp -r build/ci-release/* release/ || true
          cp ABDownloadManager.dmg release/

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          path: release
          name: app-macos

  release:
    runs-on: ubuntu-latest
    needs: [ create-packages ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-macos
          path: release

      - name: Show tree
        run: tree release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files:
            release/ABDownloadManager.dmg